---
ssh_allowed_networks: []  # noqa var-naming[no-role-prefix]
web_allowed_networks: []  # noqa var-naming[no-role-prefix]
# true borra todas las reglas nftables existentes antes de aplicar la politica
# administrada.
firewall_flush_ruleset: false  # noqa var-naming[no-role-prefix]
firewall_ssh_port: 22
firewall_web_ports: [80, 443]
firewall_postgresql_port: 5432
