#!/usr/bin/env php
<?php

use Illuminate\Foundation\Console\Kernel;

if (file_exists($autoloader = __DIR__.'/vendor/autoload.php')) {
    require $autoloader;
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
