---
- import_playbook: playbooks/validate.yml
- import_playbook: playbooks/common.yml
- import_playbook: playbooks/database.yml
- import_playbook: playbooks/runtime.yml
- import_playbook: playbooks/application.yml
- import_playbook: playbooks/scheduler.yml
- import_playbook: playbooks/tls.yml
- import_playbook: playbooks/backup.yml
- import_playbook: playbooks/security.yml
- import_playbook: playbooks/monitoring.yml
