---
php_packages:
  - php8.4-bcmath
  - php8.4-cli
  - php8.4-curl
  - php8.4-fpm
  - php8.4-gd
  - php8.4-intl
  - php8.4-mbstring
  - php8.4-opcache
  - php8.4-pgsql
  - php8.4-xml
  - php8.4-zip

php_fpm_service: php8.4-fpm
php_fpm_socket: /run/php/php8.4-fpm.sock
php_fpm_conf_dir: /etc/php/8.4/fpm/conf.d

