---
all:
  vars:
    ansible_user: deploy
    ansible_ssh_common_args: -o IdentitiesOnly=yes
    operating_system_family: debian
    operating_system_version: "13"
    web_server: apache
    web_server_version: "2.4"
    php_version: "8.4"
    postgresql_version: "17"

    ansible_ssh_private_key_file: "{{ inventory_dir }}/../../../.local/ssh/deploy_ed25519"

    application_hostname: avisos-pruebas.unlu.edu.ar
    application_url: "https://{{ application_hostname }}"
    application_release_id: "testing-2026-08-19-01"
    application_source_strategy: git
    application_git_repo: git@github.com:martin-garay/unlu_medicina_laboral.git
    application_git_ref: "{{ application_release_id }}"

    tls_enabled: true
    tls_provider: local_ca

    deploy_user_passwordless_sudo: true
    deploy_user_public_keys:
      - >-
        {{ lookup('ansible.builtin.file', inventory_dir +
        '/../../../.local/ssh/deploy_ed25519.pub') }}

    ssh_allowed_networks: []
    web_allowed_networks:
      - 0.0.0.0/0
    postgresql_allowed_networks: []

  children:
    app_servers:
      hosts:
        avisos-testing:
          ansible_host: 170.210.96.164
          application_release_id: "testing-2026-08-19-01"
          postgresql_listen_addresses:
            - 127.0.0.1
    db_servers:
      hosts:
        avisos-testing:
