---
supported_operating_systems:
  debian:
    - "13"

supported_web_servers:
  apache:
    - "2.4"

supported_php_versions:
  - "8.4"

supported_postgresql_versions:
  - "17"

php_fpm_socket: "/run/php/php{{ php_version }}-fpm.sock"

application_name: medicina-laboral
application_root: /var/www/medicina-laboral
application_release_id: workspace
application_document_root: "{{ application_root }}/current/public"
private_storage_path: /var/lib/medicina-laboral/private
backup_root: /var/backups/medicina-laboral

deploy_user_name: deploy
deploy_user_group: deploy

postgresql_database_name: medicina_laboral
postgresql_application_user: medicina_laboral

ssh_bastion_enabled: false
